### PR TITLE
Partial rewrite of SLH_QST_BimboAlias

### PR DESCRIPTION
**Pull request by ThisIsPatrick**
Rewrite of OnUpdate, OnUpdateGameTime, bimboDailyProgressiveTransformation

### CODE REVIEW

**Comment by SkyrimLL** [comment]
Too many changes to do a proper diff, so I will trust your fixes and go with them. I have a backup of the old file anyway.

**Comment by SkyrimLL** [comment]
After testing, I found the Bimbo curse unresponsive. I am troubleshooting what changed.

I noticed this variable is used but never set anywhere: _SLH_iBimboPlusON 
Is that yours?

**Comment by ThisIsPatrick** [comment]
> Too many changes to do a proper diff
The commits were separated in order to make the changes more easily readable/debuggable, although I could have done better in that regard.

> I have a backup of the old file anyway.
These changes were forked from the latest GitHub copy, why would they be outdated?

> Edit: I fixed by adding a RegisterForSingleUpdateGameTime(1) in OnPlayerLoadGame() and OnInt().
> Otherwise, the OnUpdateGameTime() event was never fired and the event loop every 24 hour was never started.

Oops! Knew I'd forgotten something.

**Comment by SkyrimLL** [comment]
They were not updated.  I only said I kept a backup in case I had to reverse course. 
Your version is working great so far so I won't have to :)

**Pull request merged**
