### PR TITLE
fctPolymorph and BimboAlias script changes implementing the shutdown of BimboAlias events

### PR DESCRIPTION
**Pull request by ThisIsPatrick**
These changes focused on implementing a endBimbo() function in the SLH_QST_BimboAlias script called from SLH_fctPolymorph through bimboTransformEffectOFF.
This allows for shutting down several events in BimboAlias (OnUpdateGameTime, OnUpdate, OnActorAction) and setting local variables back to their initial values.
The end goal of which was to ensure these events only run when the player is transformed.
This also allowed several checks to be removed from these events, as a controlled way of registering and unregistering the events made them redundant.

### CODE REVIEW

**Comment by ThisIsPatrick** [comment]
SLH_fctPolymorph.psc did not merge correctly, the file has several erroneous sections of
`>>>>>>>`
 and 
`<<<<<<<`
I don't know why it happened, my pull request was based off the latest commit. I think it had to do with all the whitespace changes I made in that file.

I'm not fluent enough in git to go about solving this, so I'm including a Gist of the file from my pull request.
https://gist.github.com/ThisIsPatrick/fd30475505702376485a76188e81cc8c

**Comment by SkyrimLL** [comment]
I made all my changes directly on the files in the Skyrim/Data/scripts/source folder and copy them into my git folder for commit and push to github.

These issues will clear themselves up the next time I edit and push the code (I will try to do that today)

**Comment by SkyrimLL** [comment]
I just pushed the code with my current files if you want to take a look.

**Comment by ThisIsPatrick** [comment]
Everything looks good.

**Comment by SkyrimLL** [comment]
Good to hear. I just pushed more scripts tweaks provided on the discussion thread at LL.

**Pull request merged**
