### PR TITLE
(Parasites) Script changes focusing on efficiency and convention

### PR DESCRIPTION
**Pull request by ThisIsPatrick**
Changed Game.GetPlayer() calls to use DD's existing libs.PlayerRef - this is convention used in all zad device scripts
Changed GetAV calls to use GetActorValue - understood to be the faster method (see [GetActorValue Notes](https://www.creationkit.com/index.php?title=GetAV_-_Actor#Notes))
HasSpell - The basics of it is that HasSpell before AddSpell is redundant. The game will handle if the spell needs to be added and you save on the time it would have took to check.
Thread post explanation of HasSpell: https://web.archive.org/web/20200213072040/http://forums.bethsoft.com/topic/1383987-performance-characteristics-of-papyrus-functions-and-operations/

### CODE REVIEW

**Comment by SkyrimLL** [comment]
Thanks.. I will take a look.

One thing about libs.playerref, do you know if DD regularly refreshes it?

I am using Game.GetPlayer() because for a while I was using the SexLab.playerref variable, until I found out it wasn't updated when the player changes race or transforms into a creature. That caused issues in several scripts.

**Comment by ThisIsPatrick** [comment]
> One thing about libs.playerref, do you know if DD regularly refreshes it? or is it set just once?
While I don't know the answer to that, if you were going to use Game.GetPlayer() instead of libs.PlayerRef in DD scripts then you should be using it in replacement of EVERY one of those calls instead of a single one half-way through a function.

> I am using Game.GetPlayer() because for a while I was using the SexLab.playerref variable, until I found out it wasn't updated when the player changes race or transforms into a creature
I can't say I've ever experienced anything like that, did you discuss it in length on LoversLab or is there more information on it availble? I'm very curious on it.
I did a small test on it a couple weeks ago, the player race of PlayerRef, SexLab.PlayerRef, and Game.GetPlayer() was always correct when checked in OnPlayerLoadGame() and in OnRaceSwitchComplete() after changing race in RaceMenu.
The only time the value was incorrect was when the reference was saved and later retrieved in StorageUtil.

**Comment by SkyrimLL** [comment]
I ran into that while working on the sex change and race changes in Hormones. 
Once the player received a different race and sex, through consoleUtil and Racemenu, SexLab.playerRef returned a different value than Game.GetPlayer().

That was a long time ago and it is very possible I misinterpreted what I was seeing.

**Comment by ThisIsPatrick** [comment]
In general, I wouldn't be as comfortable using an outside mod's property when I could set it myself in the CK for my own scripts.

**Comment by ThisIsPatrick** [comment]
If this could be reviewed and merged so that I can work on updating Parasite Devices to be compatible with the latest Devious Devices.

**Comment by ThisIsPatrick** [comment]
For some reason, pushing that last commit to resolve conflicts broke everything.
Files from the older revision I was on were also thrown in.
I might as well just start over at this point.

**Comment by SkyrimLL** [comment]
Sorry for the delay... offline work ramped up suddenly this week.
I will review these changes and incorporate them in the latest update of Parasites I am about to send out by this weekend.

**Comment by SkyrimLL** [comment]
For the simplified SexLab mod event calls, do you know how to get the list of animations and the list of actors if I need them later?
I suppose there is a function using the threadID?
I wouldn't mind applying this simplified syntax elsewhere in my mods but I am making use of the animations and actors lists in Hormones and Stories at least.

**Comment by SkyrimLL** [comment]
Nevermind.. I spoke too soon.. there is an example of both in OnSexlabEnd.

**Comment by SkyrimLL** [comment]
All the changes in this request have been merged in my end and will be in Github shortly.. and in LL later today or tomorrow. Thanks again!

**Comment by ThisIsPatrick** [comment]
Documentation for updating to the newer GetController calls from the old Hook- calls that can be searched for in the SexLab source scripts, it's all well commented in it.
For example in SexLabFramework.psc line 2790:

```
;/* HookAnimation DEPRECATED!
* * SexLab.GetController(tid).Animation
* *
* * @param: argString - The parameter received on the Event function, it is the thread ID
* * @return: a sslBaseAnimation that is the animation being played by the Controller
*/;
sslBaseAnimation function HookAnimation(string argString)
	return ThreadSlots.GetController(argString as int).Animation
endFunction
```

Actors would be on line 2820:
```
;/* HookActors DEPRECATED!
* * SexLab.GetController(tid).Positions
* *
* * @param: argString - The parameter received on the Event function, it is the thread ID
* * @return: An Actor[] with all the Positions of the SexLab animation played by the controller
*/;
Actor[] function HookActors(string argString)
	return ThreadSlots.GetController(argString as int).Positions
endFunction
```

The syntax for the newer calls usually starts with GetController(int threadID) for everything.

**Pull request closed without merging**
